// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "../ui.h"

// COMPONENT btn

lv_obj_t * ui_btn_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_btn;
    cui_btn = lv_button_create(comp_parent);
    lv_obj_set_width(cui_btn, 44);
    lv_obj_set_height(cui_btn, 25);
    lv_obj_set_x(cui_btn, -91);
    lv_obj_set_y(cui_btn, -139);
    lv_obj_set_align(cui_btn, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(cui_btn, 10);
    lv_obj_add_flag(cui_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(cui_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_btn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_btn, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_btn);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label1, "text");

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BTN_NUM);
    children[UI_COMP_BTN_BTN] = cui_btn;
    children[UI_COMP_BTN_LABEL1] = cui_Label1;
    lv_obj_add_event_cb(cui_btn, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_btn, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_btn_create_hook(cui_btn);
    return cui_btn;
}

