// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "../ui.h"

void ui_comp_btn_create_hook(lv_obj_t * comp)
{
}
