// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef _UI_COMP_BTN_H
#define _UI_COMP_BTN_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT btn
#define UI_COMP_BTN_BTN 0
#define UI_COMP_BTN_LABEL1 1
#define _UI_COMP_BTN_NUM 2
lv_obj_t * ui_btn_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
