// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef UI_SCREENMETRICS_H
#define UI_SCREENMETRICS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMetrics
extern void ui_ScreenMetrics_screen_init(void);
extern void ui_ScreenMetrics_screen_destroy(void);
extern lv_obj_t * ui_ScreenMetrics;
extern lv_obj_t * ui_Container2;
extern void ui_event_ButtonSettings_btn(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettings;
extern void ui_event_ButtonMaps_btn(lv_event_t * e);
extern lv_obj_t * ui_ButtonMaps;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_LabelTripValue;
extern lv_obj_t * ui_LabelAvgSpeedValue;
extern lv_obj_t * ui_LabelRideTimeValue;
extern lv_obj_t * ui_LabelTotalDistanceValue;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_LabelSpeedValue;
extern lv_obj_t * ui_LabelSpeedUnit;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

