// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "../ui.h"

lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_ButtonSettingsBack = NULL;
lv_obj_t * ui_ContainerSettingsList = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_DropdownUnits = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ButtonCircumferenceMinus = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_SpinboxWheelCircumference = NULL;
lv_obj_t * ui_ButtonCircumferencePlus = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_SliderBrightness = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_DropdownSleepTimeout = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_ButtonResetTrip = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_ButtonSettingsBack_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMetrics, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_ScreenMetrics_screen_init);
        cb_exit_screen_settings(e);
    }
}

void ui_event_ButtonCircumferenceMinus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxWheelCircumference, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxWheelCircumference, -1);
    }
}

void ui_event_ButtonCircumferencePlus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinboxWheelCircumference, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinboxWheelCircumference, 1);
    }
}

void ui_event_ButtonResetTrip(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cb_reset_trip(e);
    }
}

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSettings, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 230);
    lv_obj_set_height(ui_Container4, 26);
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -140);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonSettingsBack = ui_btn_create(ui_Container4);
    lv_obj_set_x(ui_ButtonSettingsBack, -46);
    lv_obj_set_y(ui_ButtonSettingsBack, -135);

    lv_label_set_text(ui_comp_get_child(ui_ButtonSettingsBack, UI_COMP_BTN_LABEL1), "");
    lv_obj_set_style_text_color(ui_comp_get_child(ui_ButtonSettingsBack, UI_COMP_BTN_LABEL1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_comp_get_child(ui_ButtonSettingsBack, UI_COMP_BTN_LABEL1), 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSettingsList = lv_obj_create(ui_ScreenSettings);
    lv_obj_remove_style_all(ui_ContainerSettingsList);
    lv_obj_set_width(ui_ContainerSettingsList, 220);
    lv_obj_set_height(ui_ContainerSettingsList, 250);
    lv_obj_set_x(ui_ContainerSettingsList, 0);
    lv_obj_set_y(ui_ContainerSettingsList, 10);
    lv_obj_set_align(ui_ContainerSettingsList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerSettingsList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerSettingsList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ContainerSettingsList, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_ContainerSettingsList, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ContainerSettingsList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ContainerSettingsList);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 219);
    lv_obj_set_height(ui_Container6, 36);
    lv_obj_set_x(ui_Container6, -51);
    lv_obj_set_y(ui_Container6, -55);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 11);
    lv_obj_set_y(ui_Label2, 10);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Units");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownUnits = lv_dropdown_create(ui_Container6);
    lv_dropdown_set_options(ui_DropdownUnits, "Metric\nImperial");
    lv_dropdown_set_selected_highlight(ui_DropdownUnits, false);
    lv_obj_set_width(ui_DropdownUnits, 98);
    lv_obj_set_height(ui_DropdownUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownUnits, 17);
    lv_obj_set_y(ui_DropdownUnits, 0);
    lv_obj_set_align(ui_DropdownUnits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownUnits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownUnits, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownUnits, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_DropdownUnits), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_DropdownUnits), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownUnits), lv_color_hex(0x242B33),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownUnits), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownUnits), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownUnits), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_ContainerSettingsList);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 220);
    lv_obj_set_height(ui_Container7, 36);
    lv_obj_set_x(ui_Container7, -57);
    lv_obj_set_y(ui_Container7, -23);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 11);
    lv_obj_set_y(ui_Label4, 10);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Circumf.");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCircumferenceMinus = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_ButtonCircumferenceMinus, 21);
    lv_obj_set_height(ui_ButtonCircumferenceMinus, 22);
    lv_obj_set_x(ui_ButtonCircumferenceMinus, 29);
    lv_obj_set_y(ui_ButtonCircumferenceMinus, -1);
    lv_obj_set_align(ui_ButtonCircumferenceMinus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCircumferenceMinus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCircumferenceMinus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCircumferenceMinus, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCircumferenceMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonCircumferenceMinus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonCircumferenceMinus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ButtonCircumferenceMinus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ButtonCircumferenceMinus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ButtonCircumferenceMinus);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "");

    ui_SpinboxWheelCircumference = lv_spinbox_create(ui_Container7);
    lv_obj_set_width(ui_SpinboxWheelCircumference, 70);
    lv_obj_set_height(ui_SpinboxWheelCircumference, 34);
    lv_obj_set_align(ui_SpinboxWheelCircumference, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SpinboxWheelCircumference, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_spinbox_set_digit_format(ui_SpinboxWheelCircumference, 4, 0);
    lv_spinbox_set_range(ui_SpinboxWheelCircumference, 1000, 2500);
    lv_spinbox_set_cursor_pos(ui_SpinboxWheelCircumference, 1 - 1);
    lv_spinbox_set_value(ui_SpinboxWheelCircumference, 2100);
    lv_obj_set_style_bg_color(ui_SpinboxWheelCircumference, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpinboxWheelCircumference, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SpinboxWheelCircumference, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SpinboxWheelCircumference, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SpinboxWheelCircumference, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCircumferencePlus = lv_button_create(ui_Container7);
    lv_obj_set_width(ui_ButtonCircumferencePlus, 21);
    lv_obj_set_height(ui_ButtonCircumferencePlus, 22);
    lv_obj_set_x(ui_ButtonCircumferencePlus, 29);
    lv_obj_set_y(ui_ButtonCircumferencePlus, -1);
    lv_obj_set_align(ui_ButtonCircumferencePlus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonCircumferencePlus, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonCircumferencePlus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonCircumferencePlus, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonCircumferencePlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonCircumferencePlus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonCircumferencePlus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ButtonCircumferencePlus, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ButtonCircumferencePlus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_ButtonCircumferencePlus);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "+");

    ui_Container8 = lv_obj_create(ui_ContainerSettingsList);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 221);
    lv_obj_set_height(ui_Container8, 36);
    lv_obj_set_x(ui_Container8, -44);
    lv_obj_set_y(ui_Container8, -55);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container8, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 11);
    lv_obj_set_y(ui_Label7, 10);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Brightness");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderBrightness = lv_slider_create(ui_Container8);
    lv_slider_set_value(ui_SliderBrightness, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_SliderBrightness, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightness, 117);
    lv_obj_set_height(ui_SliderBrightness, 10);
    lv_obj_set_x(ui_SliderBrightness, -6);
    lv_obj_set_y(ui_SliderBrightness, 0);
    lv_obj_set_align(ui_SliderBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderBrightness, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SliderBrightness, lv_color_hex(0x00AEEF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderBrightness, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderBrightness,
                                                                                                       lv_obj_get_style_pad_right(ui_SliderBrightness, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container9 = lv_obj_create(ui_ContainerSettingsList);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 219);
    lv_obj_set_height(ui_Container9, 36);
    lv_obj_set_x(ui_Container9, -51);
    lv_obj_set_y(ui_Container9, -55);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 11);
    lv_obj_set_y(ui_Label8, 10);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Sleep Timeout");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownSleepTimeout = lv_dropdown_create(ui_Container9);
    lv_dropdown_set_options(ui_DropdownSleepTimeout, "30s\n60s\n120s\n180s\n240s\n300s");
    lv_dropdown_set_selected_highlight(ui_DropdownSleepTimeout, false);
    lv_obj_set_width(ui_DropdownSleepTimeout, 77);
    lv_obj_set_height(ui_DropdownSleepTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownSleepTimeout, 17);
    lv_obj_set_y(ui_DropdownSleepTimeout, 0);
    lv_obj_set_align(ui_DropdownSleepTimeout, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownSleepTimeout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_DropdownSleepTimeout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DropdownSleepTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DropdownSleepTimeout, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DropdownSleepTimeout, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_DropdownSleepTimeout), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_DropdownSleepTimeout), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownSleepTimeout), lv_color_hex(0x242B33),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownSleepTimeout), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_ContainerSettingsList);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 216);
    lv_obj_set_height(ui_Container10, 36);
    lv_obj_set_x(ui_Container10, -51);
    lv_obj_set_y(ui_Container10, -55);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 11);
    lv_obj_set_y(ui_Label9, 10);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Reset Trip");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonResetTrip = lv_button_create(ui_Container10);
    lv_obj_set_width(ui_ButtonResetTrip, 84);
    lv_obj_set_height(ui_ButtonResetTrip, 21);
    lv_obj_set_x(ui_ButtonResetTrip, 29);
    lv_obj_set_y(ui_ButtonResetTrip, -1);
    lv_obj_set_align(ui_ButtonResetTrip, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_ButtonResetTrip, 10);
    lv_obj_add_flag(ui_ButtonResetTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonResetTrip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonResetTrip, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonResetTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_ButtonResetTrip, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_ButtonResetTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_ButtonResetTrip);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "RESET");

    lv_obj_add_event_cb(ui_ButtonSettingsBack, ui_event_ButtonSettingsBack_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCircumferenceMinus, ui_event_ButtonCircumferenceMinus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonCircumferencePlus, ui_event_ButtonCircumferencePlus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonResetTrip, ui_event_ButtonResetTrip, LV_EVENT_ALL, NULL);

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    ui_ScreenSettings = NULL;
    ui_Container4 = NULL;
    ui_ButtonSettingsBack = NULL;
    ui_ContainerSettingsList = NULL;
    ui_Container6 = NULL;
    ui_Label2 = NULL;
    ui_DropdownUnits = NULL;
    ui_Container7 = NULL;
    ui_Label4 = NULL;
    ui_ButtonCircumferenceMinus = NULL;
    ui_Label3 = NULL;
    ui_SpinboxWheelCircumference = NULL;
    ui_ButtonCircumferencePlus = NULL;
    ui_Label6 = NULL;
    ui_Container8 = NULL;
    ui_Label7 = NULL;
    ui_SliderBrightness = NULL;
    ui_Container9 = NULL;
    ui_Label8 = NULL;
    ui_DropdownSleepTimeout = NULL;
    ui_Container10 = NULL;
    ui_Label9 = NULL;
    ui_ButtonResetTrip = NULL;
    ui_Label10 = NULL;

}
