// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef UI_SCREENMAPS_H
#define UI_SCREENMAPS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMaps
extern void ui_ScreenMaps_screen_init(void);
extern void ui_ScreenMaps_screen_destroy(void);
extern void ui_event_ScreenMaps(lv_event_t * e);
extern lv_obj_t * ui_ScreenMaps;
extern lv_obj_t * ui_Container5;
extern void ui_event_ButtonMapsBack_btn(lv_event_t * e);
extern lv_obj_t * ui_ButtonMapsBack;
extern lv_obj_t * ui_MapsNoConnectedContainer;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label11;
extern void ui_event_ButtonMapsStartPairing(lv_event_t * e);
extern lv_obj_t * ui_ButtonMapsStartPairing;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_MapsConnectingContainer;
extern lv_obj_t * ui_Label13;
extern void ui_event_ButtonMapsCancelPairing(lv_event_t * e);
extern lv_obj_t * ui_ButtonMapsCancelPairing;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_MapsRenderContainer;
extern lv_obj_t * ui_MapViewport;
extern lv_obj_t * ui_LabelMapsCoordinates;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

