// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_Container4;
extern void ui_event_ButtonSettingsBack_btn(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettingsBack;
extern lv_obj_t * ui_ContainerSettingsList;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_DropdownUnits;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label4;
extern void ui_event_ButtonCircumferenceMinus(lv_event_t * e);
extern lv_obj_t * ui_ButtonCircumferenceMinus;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_SpinboxWheelCircumference;
extern void ui_event_ButtonCircumferencePlus(lv_event_t * e);
extern lv_obj_t * ui_ButtonCircumferencePlus;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_SliderBrightness;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_DropdownSleepTimeout;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label9;
extern void ui_event_ButtonResetTrip(lv_event_t * e);
extern lv_obj_t * ui_ButtonResetTrip;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

