// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "../ui.h"

lv_obj_t * ui_ScreenMaps = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_ButtonMapsBack = NULL;
lv_obj_t * ui_MapsNoConnectedContainer = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_ButtonMapsStartPairing = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_MapsConnectingContainer = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_ButtonMapsCancelPairing = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_MapsRenderContainer = NULL;
lv_obj_t * ui_MapViewport = NULL;
lv_obj_t * ui_LabelMapsCoordinates = NULL;
// event funtions
void ui_event_ButtonMapsBack_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMetrics, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_ScreenMetrics_screen_init);
        cb_exit_screen_maps(e);
    }
}

void ui_event_ButtonMapsStartPairing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cb_ble_start_pairing(e);
    }
}

void ui_event_ButtonMapsCancelPairing(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        cb_ble_cancel_pairing(e);
    }
}

// build funtions

void ui_ScreenMaps_screen_init(void)
{
    ui_ScreenMaps = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMaps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMaps, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMaps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_ScreenMaps);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 230);
    lv_obj_set_height(ui_Container5, 26);
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, -140);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonMapsBack = ui_btn_create(ui_Container5);
    lv_obj_set_x(ui_ButtonMapsBack, -46);
    lv_obj_set_y(ui_ButtonMapsBack, -135);

    lv_label_set_text(ui_comp_get_child(ui_ButtonMapsBack, UI_COMP_BTN_LABEL1), "");
    lv_obj_set_style_text_color(ui_comp_get_child(ui_ButtonMapsBack, UI_COMP_BTN_LABEL1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_comp_get_child(ui_ButtonMapsBack, UI_COMP_BTN_LABEL1), 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MapsNoConnectedContainer = lv_obj_create(ui_ScreenMaps);
    lv_obj_remove_style_all(ui_MapsNoConnectedContainer);
    lv_obj_set_width(ui_MapsNoConnectedContainer, lv_pct(100));
    lv_obj_set_height(ui_MapsNoConnectedContainer, lv_pct(100));
    lv_obj_set_align(ui_MapsNoConnectedContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MapsNoConnectedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_MapsNoConnectedContainer);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -75);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "No phone connected");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_MapsNoConnectedContainer);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 0);
    lv_obj_set_y(ui_Label11, -40);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Connect to the Android \napp to enable maps");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMapsStartPairing = lv_button_create(ui_MapsNoConnectedContainer);
    lv_obj_set_width(ui_ButtonMapsStartPairing, 104);
    lv_obj_set_height(ui_ButtonMapsStartPairing, 30);
    lv_obj_set_x(ui_ButtonMapsStartPairing, 0);
    lv_obj_set_y(ui_ButtonMapsStartPairing, 10);
    lv_obj_set_align(ui_ButtonMapsStartPairing, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMapsStartPairing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonMapsStartPairing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonMapsStartPairing, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMapsStartPairing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_ButtonMapsStartPairing);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Start Pairing");

    ui_MapsConnectingContainer = lv_obj_create(ui_ScreenMaps);
    lv_obj_remove_style_all(ui_MapsConnectingContainer);
    lv_obj_set_width(ui_MapsConnectingContainer, lv_pct(100));
    lv_obj_set_height(ui_MapsConnectingContainer, lv_pct(100));
    lv_obj_set_align(ui_MapsConnectingContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MapsConnectingContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MapsConnectingContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_MapsConnectingContainer);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -40);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Waiting for phone...");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMapsCancelPairing = lv_button_create(ui_MapsConnectingContainer);
    lv_obj_set_width(ui_ButtonMapsCancelPairing, 104);
    lv_obj_set_height(ui_ButtonMapsCancelPairing, 30);
    lv_obj_set_x(ui_ButtonMapsCancelPairing, 0);
    lv_obj_set_y(ui_ButtonMapsCancelPairing, 10);
    lv_obj_set_align(ui_ButtonMapsCancelPairing, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonMapsCancelPairing, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonMapsCancelPairing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ButtonMapsCancelPairing, lv_color_hex(0x00AEEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMapsCancelPairing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_ButtonMapsCancelPairing);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Cancel");

    ui_MapsRenderContainer = lv_obj_create(ui_ScreenMaps);
    lv_obj_remove_style_all(ui_MapsRenderContainer);
    lv_obj_set_width(ui_MapsRenderContainer, lv_pct(100));
    lv_obj_set_height(ui_MapsRenderContainer, lv_pct(100));
    lv_obj_set_align(ui_MapsRenderContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MapsRenderContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MapsRenderContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MapViewport = lv_obj_create(ui_MapsRenderContainer);
    lv_obj_remove_style_all(ui_MapViewport);
    lv_obj_set_width(ui_MapViewport, lv_pct(100));
    lv_obj_set_height(ui_MapViewport, lv_pct(85));
    lv_obj_set_x(ui_MapViewport, 0);
    lv_obj_set_y(ui_MapViewport, 20);
    lv_obj_set_align(ui_MapViewport, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MapViewport, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelMapsCoordinates = lv_label_create(ui_MapsRenderContainer);
    lv_obj_set_width(ui_LabelMapsCoordinates, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMapsCoordinates, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMapsCoordinates, 25);
    lv_obj_set_y(ui_LabelMapsCoordinates, -140);
    lv_obj_set_align(ui_LabelMapsCoordinates, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMapsCoordinates, "Lat: 34.43 | Lon: 34.43");
    lv_obj_set_style_text_color(ui_LabelMapsCoordinates, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMapsCoordinates, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonMapsBack, ui_event_ButtonMapsBack_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMapsStartPairing, ui_event_ButtonMapsStartPairing, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMapsCancelPairing, ui_event_ButtonMapsCancelPairing, LV_EVENT_ALL, NULL);

}

void ui_ScreenMaps_screen_destroy(void)
{
    if(ui_ScreenMaps) lv_obj_del(ui_ScreenMaps);

    // NULL screen variables
    ui_ScreenMaps = NULL;
    ui_Container5 = NULL;
    ui_ButtonMapsBack = NULL;
    ui_MapsNoConnectedContainer = NULL;
    ui_Label5 = NULL;
    ui_Label11 = NULL;
    ui_ButtonMapsStartPairing = NULL;
    ui_Label12 = NULL;
    ui_MapsConnectingContainer = NULL;
    ui_Label13 = NULL;
    ui_ButtonMapsCancelPairing = NULL;
    ui_Label14 = NULL;
    ui_MapsRenderContainer = NULL;
    ui_MapViewport = NULL;
    ui_LabelMapsCoordinates = NULL;

}
