// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "../ui.h"

lv_obj_t * ui_ScreenMetrics = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_ButtonSettings = NULL;
lv_obj_t * ui_ButtonMaps = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_LabelTripValue = NULL;
lv_obj_t * ui_LabelAvgSpeedValue = NULL;
lv_obj_t * ui_LabelRideTimeValue = NULL;
lv_obj_t * ui_LabelTotalDistanceValue = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_LabelSpeedValue = NULL;
lv_obj_t * ui_LabelSpeedUnit = NULL;
// event funtions
void ui_event_ButtonSettings_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_ScreenSettings_screen_init);
    }
}

void ui_event_ButtonMaps_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenMaps, LV_SCR_LOAD_ANIM_NONE, 200, 0, &ui_ScreenMaps_screen_init);
    }
}

// build funtions

void ui_ScreenMetrics_screen_init(void)
{
    ui_ScreenMetrics = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMetrics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenMetrics, lv_color_hex(0x1A2026), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMetrics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ScreenMetrics);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 230);
    lv_obj_set_height(ui_Container2, 26);
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -140);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonSettings = ui_btn_create(ui_Container2);
    lv_obj_set_x(ui_ButtonSettings, -91);
    lv_obj_set_y(ui_ButtonSettings, -139);

    lv_label_set_text(ui_comp_get_child(ui_ButtonSettings, UI_COMP_BTN_LABEL1), "");
    lv_obj_set_style_text_color(ui_comp_get_child(ui_ButtonSettings, UI_COMP_BTN_LABEL1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_comp_get_child(ui_ButtonSettings, UI_COMP_BTN_LABEL1), 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMaps = ui_btn_create(ui_Container2);
    lv_obj_set_x(ui_ButtonMaps, -40);
    lv_obj_set_y(ui_ButtonMaps, -134);

    lv_label_set_text(ui_comp_get_child(ui_ButtonMaps, UI_COMP_BTN_LABEL1), "");
    lv_obj_set_style_text_color(ui_comp_get_child(ui_ButtonMaps, UI_COMP_BTN_LABEL1), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_comp_get_child(ui_ButtonMaps, UI_COMP_BTN_LABEL1), 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_ScreenMetrics);
    lv_obj_set_width(ui_Panel3, 220);
    lv_obj_set_height(ui_Panel3, 100);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 90);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x242B33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTripValue = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelTripValue, lv_pct(33));
    lv_obj_set_height(ui_LabelTripValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTripValue, -70);
    lv_obj_set_y(ui_LabelTripValue, -24);
    lv_obj_set_align(ui_LabelTripValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTripValue, "Trip\n10.0km");
    lv_obj_set_style_text_color(ui_LabelTripValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTripValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTripValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAvgSpeedValue = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelAvgSpeedValue, lv_pct(33));
    lv_obj_set_height(ui_LabelAvgSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelAvgSpeedValue, 5);
    lv_obj_set_y(ui_LabelAvgSpeedValue, -23);
    lv_obj_set_align(ui_LabelAvgSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelAvgSpeedValue, "Avg\n50.0km");
    lv_obj_set_style_text_color(ui_LabelAvgSpeedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAvgSpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelAvgSpeedValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRideTimeValue = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelRideTimeValue, lv_pct(33));
    lv_obj_set_height(ui_LabelRideTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRideTimeValue, 55);
    lv_obj_set_y(ui_LabelRideTimeValue, -22);
    lv_obj_set_align(ui_LabelRideTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelRideTimeValue, "Time\n123:45");
    lv_obj_set_style_text_color(ui_LabelRideTimeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRideTimeValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelRideTimeValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTotalDistanceValue = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_LabelTotalDistanceValue, lv_pct(100));
    lv_obj_set_height(ui_LabelTotalDistanceValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTotalDistanceValue, 47);
    lv_obj_set_y(ui_LabelTotalDistanceValue, 10);
    lv_obj_set_align(ui_LabelTotalDistanceValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTotalDistanceValue, "Total: 234km");
    lv_obj_set_style_text_color(ui_LabelTotalDistanceValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTotalDistanceValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTotalDistanceValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_ScreenMetrics);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 240);
    lv_obj_set_height(ui_Container3, 125);
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -40);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSpeedValue = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelSpeedValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeedValue, 0);
    lv_obj_set_y(ui_LabelSpeedValue, -20);
    lv_obj_set_align(ui_LabelSpeedValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedValue, "20");
    lv_obj_set_style_text_color(ui_LabelSpeedValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeedValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedUnit = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelSpeedUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeedUnit, 0);
    lv_obj_set_y(ui_LabelSpeedUnit, 15);
    lv_obj_set_align(ui_LabelSpeedUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedUnit, "km/h");
    lv_obj_set_style_text_color(ui_LabelSpeedUnit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeedUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedUnit, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ButtonSettings, ui_event_ButtonSettings_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonMaps, ui_event_ButtonMaps_btn, LV_EVENT_ALL, NULL);

}

void ui_ScreenMetrics_screen_destroy(void)
{
    if(ui_ScreenMetrics) lv_obj_del(ui_ScreenMetrics);

    // NULL screen variables
    ui_ScreenMetrics = NULL;
    ui_Container2 = NULL;
    ui_ButtonSettings = NULL;
    ui_ButtonMaps = NULL;
    ui_Panel3 = NULL;
    ui_LabelTripValue = NULL;
    ui_LabelAvgSpeedValue = NULL;
    ui_LabelRideTimeValue = NULL;
    ui_LabelTotalDistanceValue = NULL;
    ui_Container3 = NULL;
    ui_LabelSpeedValue = NULL;
    ui_LabelSpeedUnit = NULL;

}
