// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void cb_ble_start_pairing(lv_event_t * e);
void cb_exit_screen_maps(lv_event_t * e);
void cb_ble_cancel_pairing(lv_event_t * e);
void cb_exit_screen_settings(lv_event_t * e);
void cb_reset_trip(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
