// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_BACKGROUND 0
#define UI_THEME_COLOR_CARD_BACKGROUND 1
#define UI_THEME_COLOR_SECONDARY_CARD 2
#define UI_THEME_COLOR_PRIMARY_ACCENT 3
#define UI_THEME_COLOR_MAIN_TEXT 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Background[1];
extern const ui_theme_variable_t _ui_theme_alpha_Background[1];

extern const ui_theme_variable_t _ui_theme_color_Card_Background[1];
extern const ui_theme_variable_t _ui_theme_alpha_Card_Background[1];

extern const ui_theme_variable_t _ui_theme_color_Secondary_Card[1];
extern const ui_theme_variable_t _ui_theme_alpha_Secondary_Card[1];

extern const ui_theme_variable_t _ui_theme_color_Primary_Accent[1];
extern const ui_theme_variable_t _ui_theme_alpha_Primary_Accent[1];

extern const ui_theme_variable_t _ui_theme_color_Main_Text[1];
extern const ui_theme_variable_t _ui_theme_alpha_Main_Text[1];

extern const uint32_t * ui_theme_colors[1];
extern const uint8_t * ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
