// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: bike_computer_ui

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Background[1] = {0x101418};
const ui_theme_variable_t _ui_theme_alpha_Background[1] = {255};

const ui_theme_variable_t _ui_theme_color_Card_Background[1] = {0x1A2026};
const ui_theme_variable_t _ui_theme_alpha_Card_Background[1] = {255};

const ui_theme_variable_t _ui_theme_color_Secondary_Card[1] = {0x242B33};
const ui_theme_variable_t _ui_theme_alpha_Secondary_Card[1] = {255};

const ui_theme_variable_t _ui_theme_color_Primary_Accent[1] = {0x00AEEF};
const ui_theme_variable_t _ui_theme_alpha_Primary_Accent[1] = {255};

const ui_theme_variable_t _ui_theme_color_Main_Text[1] = {0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_Main_Text[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

